version: "3.8"
services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafanac
    ports:
      - "3000:3000"
    volumes:
      - grafanav:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
  tsdb:
    image: influxdb:1.8
    container_name: tsdbc
    ports:
      - "8086:8086"
    volumes:
      - tsdbv:/var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
volumes:
  grafanav:
  tsdbv:
